apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo
  namespace: default
  labels:
    app.kubernetes.io/name: go-demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.demo: "semver:~v1.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-demo
    spec:
      containers:
        - name: demo
          image: devopsws/go-server:v0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
