name: Build

on:
  - pull_request

jobs:
  Image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v2.3.0
      with:
        images: devopsws/go-server
        tag-sha: false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        file: Dockerfile.multiStage
        push: true
        platforms: linux/amd64,linux/arm64
    - name: Start Server
      run: |
        docker run -d -p 8899:8899 ${{ steps.docker_meta.outputs.tags }}
        curl https://github.com/LinuxSuRen/api-testing/releases/download/v0.0.11/atest-linux-amd64.tar.gz -L -o atest-linux-amd64.tar.gz
        tar xzvf atest-linux-amd64.tar.gz atest
        ./atest run -p testing/*.yaml